name: pre-commit

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.15
        with:
          source-folder: 'src/cvx'
          tests-folder: 'src/tests'

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/deptry@v2.0.15
        with:
          source-folder: 'src/cvx'


  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/pre-commit@v2.0.15
